spring:
  application:
    name: SpringProject17_ServiceRegistry

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost
#    prefer-ip-address: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000