server:
 port: 8083

spring:
  application:
    name: RATING-SERVICE
  config:
    import: optional:configserver:http://localhost:8085

  data:
    mongodb:
      uri: mongodb://admin:qwerty@localhost:27017
      database: spring_micro
      username: admin
      password: qwerty


#    redis:
#      host: localhost
#      port: 6379
#  cache:
#    type: redis

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8086

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: always